### ISSUE TITLE
Metavoice is only english, what about using it with other TTS generations?

### ISSUE THREAD

**Issue by juangea** [tonychenxyz/emoknob#3]
For example, MeloTTS is good at genearting text in several languages, but pretty but in emotion, could this be sued as a post.-process to add emotion to an already generated voice?

Thanks!

**Comment by tonychenxyz** [comment]
Thanks for your interest! It seems like MeloTTS does't allow embedding-based zero-shot voice cloning, so it's not compatible with EmoKnob. But you can try out multilingual zero-shot voice cloning models such as [XTTS](https://arxiv.org/pdf/2406.04904).

**Comment by juangea** [comment]
XTTS is not a good choice, the license is impossible to use for anything that it’s not just a home hobby, and it’s impossible to acquire any other license.

could this be used with Bark or Toucan?

**Comment by tonychenxyz** [comment]
Bark seems to have disabled their voice cloning api. Also they are not embedding based so I don't think it's compatible.
I checked out Toucan TTS, seems like that they already supports style transfer? https://toucanprosodycloningdemo.github.io

**Comment by tonychenxyz** [comment]
Hi @juangea ! MetaVoice has support for finetuning for different languages: https://huggingface.co/metavoiceio/metavoice-1B-v0.1/discussions/9
Maybe you can try that and use EmoKnob on fine-tuned model
