### ISSUE TITLE
Question: length of audio files

### ISSUE THREAD

**Issue by Natalie-Caruana** [tonychenxyz/emoknob#5]
Hi,

How long were the audio file pairs that you used as one shot examples for the simple emotions?

Thanks!
Natalie

**Comment by tonychenxyz** [comment]
Thanks for your interest!
For simple emotions, we used longer clips such as 3-10 minutes (concatenating all clips of an emotion of a speaker in MSP-Podcast dataset).
For complex emotions and synthetic data, clips are mostly under 1 minutes.
